#!/usr/bin/with-contenv bash
echo "$( date +'%Y/%m/%d %H:%M:%S' ) Mounting in ${MOUNT_DIR}"

_cmd="sshfs \
      -o allow_other,\
      default_permissions,\
      IdentityFile=/ssh/${ID_FILE},\
      port=${PORT} \
      ${ADDRESS} \
      ${MOUNT_DIR}"

echo "${_cmd}"	

exec $(echo ${_cmd}) 
